import {
	accordion01Code,
	Accordion01Component,
	accordion02Code,
	Accordion02Component,
	accordion03Code,
	Accordion03Component,
	accordion04Code,
	Accordion04Component,
	accordion05Code,
	Accordion05Component,
	accordion06Code,
	Accordion06Component,
	accordion07Code,
	Accordion07Component,
	accordion08Code,
	Accordion08Component,
	accordion09Code,
	Accordion09Component,
	accordion10Code,
	Accordion10Component,
	accordion11Code,
	Accordion11Component,
	accordion12Code,
	Accordion12Component,
	accordion13Code,
	Accordion13Component,
	accordion14Code,
	Accordion14Component,
	accordion15Code,
	Accordion15Component,
	accordion16Code,
	Accordion16Component,
	accordion17Code,
	Accordion17Component,
	accordion18Code,
	Accordion18Component,
	accordion19Code,
	Accordion19Component,
	accordion20Code,
	Accordion20Component,
} from '../components/accordion';
import { ComponentCardItem } from '../core';

export const accordionComponents: ComponentCardItem[] = [
	{
		id: 'accordion-01',
		component: Accordion01Component,
		code: accordion01Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-02',
		component: Accordion02Component,
		code: accordion02Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-03',
		component: Accordion03Component,
		code: accordion03Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-04',
		component: Accordion04Component,
		code: accordion04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-05',
		component: Accordion05Component,
		code: accordion05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-06',
		component: Accordion06Component,
		code: accordion06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-07',
		component: Accordion07Component,
		code: accordion07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-08',
		component: Accordion08Component,
		code: accordion08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-09',
		component: Accordion09Component,
		code: accordion09Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-10',
		component: Accordion10Component,
		code: accordion10Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-11',
		component: Accordion11Component,
		code: accordion11Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-12',
		component: Accordion12Component,
		code: accordion12Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-13',
		component: Accordion13Component,
		code: accordion13Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-14',
		component: Accordion14Component,
		code: accordion14Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-15',
		component: Accordion15Component,
		code: accordion15Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-16',
		component: Accordion16Component,
		code: accordion16Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-17',
		component: Accordion17Component,
		code: accordion17Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-18',
		component: Accordion18Component,
		code: accordion18Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-19',
		component: Accordion19Component,
		code: accordion19Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-20',
		component: Accordion20Component,
		code: accordion20Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
