import {
	Accordion01Component,
	Accordion02Component,
	Accordion03Component,
	Accordion04Component,
	Accordion05Component,
	Accordion06Component,
	Accordion07Component,
	Accordion08Component,
	Accordion09Component,
	Accordion10Component,
	Accordion11Component,
	Accordion12Component,
	Accordion13Component,
	Accordion14Component,
	Accordion15Component,
	Accordion16Component,
	Accordion17Component,
	Accordion18Component,
	Accordion19Component,
	Accordion20Component,
	Accordion21Component,
	Accordion22Component,
} from '../components/accordion';
import { ComponentCardItem } from '../core';

export const accordionComponents: ComponentCardItem[] = [
	{
		id: 'accordion-01',
		component: Accordion01Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-02',
		component: Accordion02Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-03',
		component: Accordion03Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-04',
		component: Accordion04Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-05',
		component: Accordion05Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-06',
		component: Accordion06Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-07',
		component: Accordion07Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-08',
		component: Accordion08Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-09',
		component: Accordion09Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-10',
		component: Accordion10Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-11',
		component: Accordion11Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-12',
		component: Accordion12Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-13',
		component: Accordion13Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-14',
		component: Accordion14Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-15',
		component: Accordion15Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-16',
		component: Accordion16Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-17',
		component: Accordion17Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-18',
		component: Accordion18Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-19',
		component: Accordion19Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-20',
		component: Accordion20Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-21',
		component: Accordion21Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'accordion-22',
		component: Accordion22Component,
		colNumber: 2,
		itemStyle: 1,
	},
];
