import {
	Alert01Component,
	Alert02Component,
	Alert03Component,
	Alert04Component,
	Alert05Component,
	Alert06Component,
	Alert07Component,
	Alert08Component,
	Alert09Component,
	Alert10Component,
	Alert11Component,
	Alert12Component,
	Alert13Component,
	Alert14Component,
	Alert15Component,
	Alert16Component,
	Alert17Component,
	Alert18Component,
} from '../components/alert';
import { ComponentCardItem } from '../core';

export const alertComponents: ComponentCardItem[] = [
	{
		id: 'alert-01',
		component: Alert01Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-02',
		component: Alert02Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-03',
		component: Alert03Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-04',
		component: Alert04Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-05',
		component: Alert05Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-06',
		component: Alert06Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-07',
		component: Alert07Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-08',
		component: Alert08Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-09',
		component: Alert09Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-10',
		component: Alert10Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-11',
		component: Alert11Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-12',
		component: Alert12Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-13',
		component: Alert13Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-14',
		component: Alert14Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-15',
		component: Alert15Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-16',
		component: Alert16Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-17',
		component: Alert17Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-18',
		component: Alert18Component,
		colNumber: 2,
		itemStyle: 1,
	},
];
