import {
	Alert01Component,
	Alert02Component,
	Alert03Component,
	Alert04Component,
	Alert05Component,
	Alert06Component,
	Alert07Component,
	Alert08Component,
	Alert09Component,
	Alert10Component,
	Alert11Component,
	Alert12Component,
	Alert13Component,
	Alert14Component,
	Alert15Component,
	Alert16Component,
	Alert17Component,
	Alert18Component,
	alert01Code,
	alert02Code,
	alert03Code,
	alert04Code,
	alert05Code,
	alert06Code,
	alert07Code,
	alert08Code,
	alert09Code,
	alert10Code,
	alert11Code,
	alert12Code,
	alert13Code,
	alert14Code,
	alert15Code,
	alert16Code,
	alert17Code,
	alert18Code,
} from '../components/alert';
import { ComponentCardItem } from '../core';

export const alertComponents: ComponentCardItem[] = [
	{
		id: 'alert-01',
		component: Alert01Component,
		code: alert01Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-02',
		component: Alert02Component,
		code: alert02Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-03',
		component: Alert03Component,
		code: alert03Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-04',
		component: Alert04Component,
		code: alert04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-05',
		component: Alert05Component,
		code: alert05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-06',
		component: Alert06Component,
		code: alert06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-07',
		component: Alert07Component,
		code: alert07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-08',
		component: Alert08Component,
		code: alert08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-09',
		component: Alert09Component,
		code: alert09Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-10',
		component: Alert10Component,
		code: alert10Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-11',
		component: Alert11Component,
		code: alert11Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-12',
		component: Alert12Component,
		code: alert12Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-13',
		component: Alert13Component,
		code: alert13Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-14',
		component: Alert14Component,
		code: alert14Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-15',
		component: Alert15Component,
		code: alert15Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-16',
		component: Alert16Component,
		code: alert16Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-17',
		component: Alert17Component,
		code: alert17Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'alert-18',
		component: Alert18Component,
		code: alert18Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
