import {
	Avatar01Component,
	Avatar02Component,
	Avatar03Component,
	Avatar04Component,
	Avatar05Component,
	Avatar06Component,
	Avatar07Component,
	Avatar08Component,
	Avatar09Component,
	Avatar10Component,
	Avatar11Component,
	Avatar12Component,
	Avatar13Component,
	Avatar14Component,
	Avatar15Component,
	Avatar16Component,
	Avatar17Component,
	Avatar18Component,
	Avatar19Component,
	Avatar20Component,
	Avatar21Component,
	Avatar22Component,
} from '../components/avatar';
import { ComponentCardItem } from '../core';

export const avatarComponents: ComponentCardItem[] = [
	{
		component: Avatar01Component,
		id: 'avatar-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar02Component,
		id: 'avatar-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar03Component,
		id: 'avatar-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar04Component,
		id: 'avatar-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar05Component,
		id: 'avatar-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar06Component,
		id: 'avatar-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar07Component,
		id: 'avatar-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar08Component,
		id: 'avatar-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar09Component,
		id: 'avatar-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar10Component,
		id: 'avatar-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar11Component,
		id: 'avatar-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar12Component,
		id: 'avatar-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar13Component,
		id: 'avatar-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar14Component,
		id: 'avatar-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar22Component,
		id: 'avatar-22',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar15Component,
		id: 'avatar-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar16Component,
		id: 'avatar-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar17Component,
		id: 'avatar-17',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar18Component,
		id: 'avatar-18',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar19Component,
		id: 'avatar-19',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar20Component,
		id: 'avatar-20',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar21Component,
		id: 'avatar-21',
		colNumber: 4,
		itemStyle: 1,
	},
];
