import {
	avatar01Code,
	Avatar01Component,
	avatar02Code,
	Avatar02Component,
	avatar03Code,
	Avatar03Component,
	avatar04Code,
	Avatar04Component,
	avatar05Code,
	Avatar05Component,
	avatar06Code,
	Avatar06Component,
	avatar07Code,
	Avatar07Component,
	avatar08Code,
	Avatar08Component,
	avatar09Code,
	Avatar09Component,
	avatar10Code,
	Avatar10Component,
	avatar11Code,
	Avatar11Component,
	avatar12Code,
	Avatar12Component,
	avatar13Code,
	Avatar13Component,
	avatar14Code,
	Avatar14Component,
	avatar15Code,
	Avatar15Component,
	avatar16Code,
	Avatar16Component,
	avatar17Code,
	Avatar17Component,
	avatar18Code,
	Avatar18Component,
	avatar19Code,
	Avatar19Component,
	avatar20Code,
	Avatar20Component,
	avatar21Code,
	Avatar21Component,
} from '../components/avatar';
import { ComponentCardItem } from '../core';

export const avatarComponents: ComponentCardItem[] = [
	{
		component: Avatar01Component,
		code: avatar01Code,
		id: 'avatar-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar02Component,
		code: avatar02Code,
		id: 'avatar-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar03Component,
		code: avatar03Code,
		id: 'avatar-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar04Component,
		code: avatar04Code,
		id: 'avatar-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar05Component,
		code: avatar05Code,
		id: 'avatar-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar06Component,
		code: avatar06Code,
		id: 'avatar-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar07Component,
		code: avatar07Code,
		id: 'avatar-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar08Component,
		code: avatar08Code,
		id: 'avatar-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar09Component,
		code: avatar09Code,
		id: 'avatar-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar10Component,
		code: avatar10Code,
		id: 'avatar-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar11Component,
		code: avatar11Code,
		id: 'avatar-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar12Component,
		code: avatar12Code,
		id: 'avatar-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar13Component,
		code: avatar13Code,
		id: 'avatar-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar14Component,
		code: avatar14Code,
		id: 'avatar-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar15Component,
		code: avatar15Code,
		id: 'avatar-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar16Component,
		code: avatar16Code,
		id: 'avatar-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar17Component,
		code: avatar17Code,
		id: 'avatar-17',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar18Component,
		code: avatar18Code,
		id: 'avatar-18',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar19Component,
		code: avatar19Code,
		id: 'avatar-19',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar20Component,
		code: avatar20Code,
		id: 'avatar-20',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Avatar21Component,
		code: avatar21Code,
		id: 'avatar-21',
		colNumber: 4,
		itemStyle: 1,
	},
];
