import {
	Badge01Component,
	Badge02Component,
	Badge03Component,
	Badge04Component,
	Badge05Component,
	Badge06Component,
	Badge07Component,
	Badge08Component,
	Badge09Component,
	Badge10Component,
	Badge11Component,
	Badge12Component,
	Badge13Component,
	Badge14Component,
	Badge15Component,
	Badge16Component,
	Badge17Component,
	Badge18Component,
	Badge19Component,
	Badge20Component,
	Badge21Component,
	Badge22Component,
	Badge23Component,
	badge01Code,
	badge02Code,
	badge03Code,
	badge04Code,
	badge05Code,
	badge06Code,
	badge07Code,
	badge08Code,
	badge09Code,
	badge10Code,
	badge11Code,
	badge12Code,
	badge13Code,
	badge14Code,
	badge15Code,
	badge16Code,
	badge17Code,
	badge18Code,
	badge19Code,
	badge20Code,
	badge21Code,
	badge22Code,
	badge23Code,
} from '../components/badge';
import { ComponentCardItem } from '../core';

export const badgeComponents: ComponentCardItem[] = [
	{
		id: 'badge-01',
		component: Badge01Component,
		code: badge01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-02',
		component: Badge02Component,
		code: badge02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-03',
		component: Badge03Component,
		code: badge03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-04',
		component: Badge04Component,
		code: badge04Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-05',
		component: Badge05Component,
		code: badge05Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-06',
		component: Badge06Component,
		code: badge06Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-07',
		component: Badge07Component,
		code: badge07Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-08',
		component: Badge08Component,
		code: badge08Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-09',
		component: Badge09Component,
		code: badge09Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-10',
		component: Badge10Component,
		code: badge10Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-11',
		component: Badge11Component,
		code: badge11Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-12',
		component: Badge12Component,
		code: badge12Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-13',
		component: Badge13Component,
		code: badge13Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-14',
		component: Badge14Component,
		code: badge14Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-15',
		component: Badge15Component,
		code: badge15Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-16',
		component: Badge16Component,
		code: badge16Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-17',
		component: Badge17Component,
		code: badge17Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-18',
		component: Badge18Component,
		code: badge18Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-19',
		component: Badge19Component,
		code: badge19Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-20',
		component: Badge20Component,
		code: badge20Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-21',
		component: Badge21Component,
		code: badge21Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-22',
		component: Badge22Component,
		code: badge22Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-23',
		component: Badge23Component,
		code: badge23Code,
		colNumber: 4,
		itemStyle: 1,
	},
];
