import {
	Badge01Component,
	Badge02Component,
	Badge03Component,
	Badge04Component,
	Badge05Component,
	Badge06Component,
	Badge07Component,
	Badge08Component,
	Badge09Component,
	Badge10Component,
	Badge11Component,
	Badge12Component,
	Badge13Component,
	Badge14Component,
	Badge15Component,
	Badge16Component,
	Badge17Component,
	Badge18Component,
	Badge19Component,
	Badge20Component,
	Badge21Component,
	Badge22Component,
	Badge23Component,
} from '../components/badge';
import { ComponentCardItem } from '../core';

export const badgeComponents: ComponentCardItem[] = [
	{
		id: 'badge-01',
		component: Badge01Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-02',
		component: Badge02Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-03',
		component: Badge03Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-04',
		component: Badge04Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-05',
		component: Badge05Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-06',
		component: Badge06Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-07',
		component: Badge07Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-08',
		component: Badge08Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-09',
		component: Badge09Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-10',
		component: Badge10Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-11',
		component: Badge11Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-12',
		component: Badge12Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-13',
		component: Badge13Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-14',
		component: Badge14Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-15',
		component: Badge15Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-16',
		component: Badge16Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-17',
		component: Badge17Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-18',
		component: Badge18Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-19',
		component: Badge19Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-20',
		component: Badge20Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-21',
		component: Badge21Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-22',
		component: Badge22Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'badge-23',
		component: Badge23Component,
		colNumber: 4,
		itemStyle: 1,
	},
];
