import {
	Banner01Component,
	Banner02Component,
	Banner03Component,
	Banner04Component,
	Banner05Component,
	Banner06Component,
	Banner07Component,
	Banner08Component,
	Banner09Component,
	Banner10Component,
	Banner11Component,
	banner01Code,
	banner02Code,
	banner03Code,
	banner04Code,
	banner05Code,
	banner06Code,
	banner07Code,
	banner08Code,
	banner09Code,
	banner10Code,
	banner11Code,
} from '../components/banner';
import { ComponentCardItem } from '../core';

export const bannerComponents: ComponentCardItem[] = [
	{
		id: 'banner-01',
		component: Banner01Component,
		code: banner01Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-02',
		component: Banner02Component,
		code: banner02Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-03',
		component: Banner03Component,
		code: banner03Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-04',
		component: Banner04Component,
		code: banner04Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-05',
		component: Banner05Component,
		code: banner05Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-06',
		component: Banner06Component,
		code: banner06Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-07',
		component: Banner07Component,
		code: banner07Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-08',
		component: Banner08Component,
		code: banner08Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-09',
		component: Banner09Component,
		code: banner09Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-10',
		component: Banner10Component,
		code: banner10Code,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'banner-11',
		component: Banner11Component,
		code: banner11Code,
		colNumber: 3,
		itemStyle: 1,
	},
];
