import {
	Breadcrumb01Component,
	Breadcrumb02Component,
	Breadcrumb03Component,
	Breadcrumb04Component,
	Breadcrumb05Component,
	Breadcrumb06Component,
	Breadcrumb07Component,
	Breadcrumb08Component,
	Breadcrumb09Component,
	breadcrumb01Code,
	breadcrumb02Code,
	breadcrumb03Code,
	breadcrumb04Code,
	breadcrumb05Code,
	breadcrumb06Code,
	breadcrumb07Code,
	breadcrumb08Code,
	breadcrumb09Code,
} from '../components/breadcrumb';
import { ComponentCardItem } from '../core';

export const breadcrumbComponents: ComponentCardItem[] = [
	{
		id: 'breadcrumb-01',
		component: Breadcrumb01Component,
		code: breadcrumb01Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-02',
		component: Breadcrumb02Component,
		code: breadcrumb02Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-03',
		component: Breadcrumb03Component,
		code: breadcrumb03Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-04',
		component: Breadcrumb04Component,
		code: breadcrumb04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-05',
		component: Breadcrumb05Component,
		code: breadcrumb05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-06',
		component: Breadcrumb06Component,
		code: breadcrumb06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-07',
		component: Breadcrumb07Component,
		code: breadcrumb07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-08',
		component: Breadcrumb08Component,
		code: breadcrumb08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'breadcrumb-09',
		component: Breadcrumb09Component,
		code: breadcrumb09Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
