import {
	Button01Component,
	Button02Component,
	Button03Component,
	Button04Component,
	Button05Component,
	Button06Component,
	Button07Component,
	Button08Component,
	Button09Component,
	Button10Component,
	Button11Component,
	Button12Component,
	Button13Component,
	Button14Component,
	Button15Component,
	Button16Component,
	Button17Component,
	Button18Component,
	Button19Component,
	Button20Component,
	Button21Component,
	Button22Component,
	Button23Component,
	Button24Component,
	Button25Component,
	Button26Component,
	Button27Component,
	Button28Component,
	Button29Component,
	Button30Component,
	Button31Component,
	Button32Component,
	Button33Component,
	Button34Component,
	Button35Component,
	Button36Component,
	Button37Component,
	Button38Component,
	Button39Component,
	Button40Component,
	Button41Component,
	Button42Component,
	Button43Component,
	Button44Component,
	Button45Component,
	Button46Component,
	Button47Component,
	Button48Component,
	Button49Component,
	Button50Component,
	Button51Component,
	Button52Component,
	Button53Component,
	Button54Component,
} from '../components/button';
import { ComponentCardItem } from '../core';

export const buttonComponents: ComponentCardItem[] = [
	{
		id: 'button-01',
		component: Button01Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-05',
		component: Button05Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-03',
		component: Button03Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-04',
		component: Button04Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-02',
		component: Button02Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-06',
		component: Button06Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-07',
		component: Button07Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-08',
		component: Button08Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-09',
		component: Button09Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-10',
		component: Button10Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-11',
		component: Button11Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-12',
		component: Button12Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-13',
		component: Button13Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-14',
		component: Button14Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-15',
		component: Button15Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-16',
		component: Button16Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-17',
		component: Button17Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-18',
		component: Button18Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-19',
		component: Button19Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-20',
		component: Button20Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-21',
		component: Button21Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-22',
		component: Button22Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-23',
		component: Button23Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-24',
		component: Button24Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-25',
		component: Button25Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-26',
		component: Button26Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-27',
		component: Button27Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-28',
		component: Button28Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-29',
		component: Button29Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-30',
		component: Button30Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-31',
		component: Button31Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-32',
		component: Button32Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-33',
		component: Button33Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-34',
		component: Button34Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-35',
		component: Button35Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-36',
		component: Button36Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-37',
		component: Button37Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-38',
		component: Button38Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-39',
		component: Button39Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-40',
		component: Button40Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-41',
		component: Button41Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-42',
		component: Button42Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-43',
		component: Button43Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-44',
		component: Button44Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-45',
		component: Button45Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-46',
		component: Button46Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-47',
		component: Button47Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-48',
		component: Button48Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-49',
		component: Button49Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-50',
		component: Button50Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-51',
		component: Button51Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-52',
		component: Button52Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-53',
		component: Button53Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-54',
		component: Button54Component,
		colNumber: 4,
		itemStyle: 1,
	},
];
