import {
	Button01Component,
	Button02Component,
	Button03Component,
	Button04Component,
	Button05Component,
	Button06Component,
	Button07Component,
	Button08Component,
	Button09Component,
	Button10Component,
	Button11Component,
	Button12Component,
	Button13Component,
	Button14Component,
	Button15Component,
	Button16Component,
	Button17Component,
	Button18Component,
	Button19Component,
	Button20Component,
	Button21Component,
	Button22Component,
	Button23Component,
	Button24Component,
	Button25Component,
	Button26Component,
	Button27Component,
	Button28Component,
	Button29Component,
	Button30Component,
	Button31Component,
	Button32Component,
	Button33Component,
	Button34Component,
	Button35Component,
	Button36Component,
	Button37Component,
	Button38Component,
	Button39Component,
	Button40Component,
	Button41Component,
	Button42Component,
	Button43Component,
	Button44Component,
	Button45Component,
	Button46Component,
	Button47Component,
	Button48Component,
	Button49Component,
	Button50Component,
	Button51Component,
	Button52Component,
	Button53Component,
	Button54Component,
	button01Code,
	button02Code,
	button03Code,
	button04Code,
	button05Code,
	button06Code,
	button07Code,
	button08Code,
	button09Code,
	button10Code,
	button11Code,
	button12Code,
	button13Code,
	button14Code,
	button15Code,
	button16Code,
	button17Code,
	button18Code,
	button19Code,
	button20Code,
	button21Code,
	button22Code,
	button23Code,
	button24Code,
	button25Code,
	button26Code,
	button27Code,
	button28Code,
	button29Code,
	button30Code,
	button31Code,
	button32Code,
	button33Code,
	button34Code,
	button35Code,
	button36Code,
	button37Code,
	button38Code,
	button39Code,
	button40Code,
	button41Code,
	button42Code,
	button43Code,
	button44Code,
	button45Code,
	button46Code,
	button47Code,
	button48Code,
	button49Code,
	button50Code,
	button51Code,
	button52Code,
	button53Code,
	button54Code,
} from '../components/button';
import { ComponentCardItem } from '../core';

export const buttonComponents: ComponentCardItem[] = [
	{
		id: 'button-01',
		component: Button01Component,
		code: button01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-05',
		component: Button05Component,
		code: button05Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-03',
		component: Button03Component,
		code: button03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-04',
		component: Button04Component,
		code: button04Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-02',
		component: Button02Component,
		code: button02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-06',
		component: Button06Component,
		code: button06Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-07',
		component: Button07Component,
		code: button07Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-08',
		component: Button08Component,
		code: button08Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-09',
		component: Button09Component,
		code: button09Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-10',
		component: Button10Component,
		code: button10Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-11',
		component: Button11Component,
		code: button11Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-12',
		component: Button12Component,
		code: button12Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-13',
		component: Button13Component,
		code: button13Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-14',
		component: Button14Component,
		code: button14Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-15',
		component: Button15Component,
		code: button15Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-16',
		component: Button16Component,
		code: button16Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-17',
		component: Button17Component,
		code: button17Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-18',
		component: Button18Component,
		code: button18Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-19',
		component: Button19Component,
		code: button19Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-20',
		component: Button20Component,
		code: button20Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-21',
		component: Button21Component,
		code: button21Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-22',
		component: Button22Component,
		code: button22Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-23',
		component: Button23Component,
		code: button23Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-24',
		component: Button24Component,
		code: button24Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-25',
		component: Button25Component,
		code: button25Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-26',
		component: Button26Component,
		code: button26Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-27',
		component: Button27Component,
		code: button27Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-28',
		component: Button28Component,
		code: button28Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-29',
		component: Button29Component,
		code: button29Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-30',
		component: Button30Component,
		code: button30Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-31',
		component: Button31Component,
		code: button31Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-32',
		component: Button32Component,
		code: button32Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-33',
		component: Button33Component,
		code: button33Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-34',
		component: Button34Component,
		code: button34Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-35',
		component: Button35Component,
		code: button35Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-36',
		component: Button36Component,
		code: button36Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-37',
		component: Button37Component,
		code: button37Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-38',
		component: Button38Component,
		code: button38Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-39',
		component: Button39Component,
		code: button39Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-40',
		component: Button40Component,
		code: button40Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-41',
		component: Button41Component,
		code: button41Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-42',
		component: Button42Component,
		code: button42Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-43',
		component: Button43Component,
		code: button43Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-44',
		component: Button44Component,
		code: button44Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-45',
		component: Button45Component,
		code: button45Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-46',
		component: Button46Component,
		code: button46Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-47',
		component: Button47Component,
		code: button47Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-48',
		component: Button48Component,
		code: button48Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-49',
		component: Button49Component,
		code: button49Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-50',
		component: Button50Component,
		code: button50Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-51',
		component: Button51Component,
		code: button51Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-52',
		component: Button52Component,
		code: button52Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-53',
		component: Button53Component,
		code: button53Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'button-54',
		component: Button54Component,
		code: button54Code,
		colNumber: 4,
		itemStyle: 1,
	},
];
