import {
	Calendar01Component,
	Calendar02Component,
	Calendar03Component,
	Calendar04Component,
	Calendar05Component,
	Calendar06Component,
	Calendar07Component,
	Calendar08Component,
	Calendar09Component,
	Calendar10Component,
	Calendar11Component,
	Calendar12Component,
	Calendar13Component,
	Calendar14Component,
	Calendar15Component,
	Calendar16Component,
	Calendar17Component,
	Calendar18Component,
	Calendar19Component,
} from '../components/calendar';
import { ComponentCardItem } from '../core';

export const calendarComponents: ComponentCardItem[] = [
	{
		id: 'calendar-01',
		component: Calendar01Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-02',
		component: Calendar02Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-03',
		component: Calendar03Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-04',
		component: Calendar04Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-05',
		component: Calendar05Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-06',
		component: Calendar06Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-07',
		component: Calendar07Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-08',
		component: Calendar08Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-09',
		component: Calendar09Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'calendar-10',
		component: Calendar10Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'calendar-11',
		component: Calendar11Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'calendar-12',
		component: Calendar12Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'calendar-13',
		component: Calendar13Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'calendar-14',
		component: Calendar14Component,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'calendar-15',
		component: Calendar15Component,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'calendar-16',
		component: Calendar16Component,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'calendar-17',
		component: Calendar17Component,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'calendar-18',
		component: Calendar18Component,
		colNumber: 3,
		itemStyle: 1,
	},
	{
		id: 'calendar-19',
		component: Calendar19Component,
		colNumber: 3,
		itemStyle: 1,
	},
];
