import {
	card01Code,
	Card01Component,
	card02Code,
	Card02Component,
	card03Code,
	Card03Component,
	card04Code,
	Card04Component,
	card05Code,
	Card05Component,
	card06Code,
	Card06Component,
	card07Code,
	Card07Component,
	card08Code,
	Card08Component,
	card09Code,
	Card09Component,
	card10Code,
	Card10Component,
	card11Code,
	Card11Component,
} from '@/app/components/card';
import { ComponentCardItem } from '../core';

export const cardComponents: ComponentCardItem[] = [
	{
		component: Card03Component,
		code: card03Code,
		id: 'card-03',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card06Component,
		code: card06Code,
		id: 'card-06',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card10Component,
		code: card10Code,
		id: 'card-10',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card11Component,
		code: card11Code,
		id: 'card-11',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card01Component,
		code: card01Code,
		id: 'card-01',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card09Component,
		code: card09Code,
		id: 'card-09',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card02Component,
		code: card02Code,
		id: 'card-02',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card04Component,
		code: card04Code,
		id: 'card-04',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card05Component,
		code: card05Code,
		id: 'card-05',
		colNumber: 2,
		itemStyle: 1,
	},

	{
		component: Card07Component,
		code: card07Code,
		id: 'card-07',
		colNumber: 2,
		itemStyle: 1,
	},
	{
		component: Card08Component,
		code: card08Code,
		id: 'card-08',
		colNumber: 2,
		itemStyle: 1,
	},
];
