import {
	Checkbox01Component,
	Checkbox02Component,
	Checkbox03Component,
	Checkbox04Component,
	Checkbox05Component,
	Checkbox06Component,
	Checkbox07Component,
	Checkbox08Component,
	Checkbox09Component,
	Checkbox10Component,
	Checkbox11Component,
	Checkbox12Component,
	Checkbox13Component,
	Checkbox14Component,
	Checkbox15Component,
	Checkbox16Component,
	Checkbox17Component,
	Checkbox18Component,
	Checkbox19Component,
	Checkbox20Component,
	Checkbox21Component,
	Checkbox22Component,
	checkbox01Code,
	checkbox02Code,
	checkbox03Code,
	checkbox04Code,
	checkbox05Code,
	checkbox06Code,
	checkbox07Code,
	checkbox08Code,
	checkbox09Code,
	checkbox10Code,
	checkbox11Code,
	checkbox12Code,
	checkbox13Code,
	checkbox14Code,
	checkbox15Code,
	checkbox16Code,
	checkbox17Code,
	checkbox18Code,
	checkbox19Code,
	checkbox20Code,
	checkbox21Code,
	checkbox22Code,
} from '../components/checkbox';
import { ComponentCardItem } from '../core';

export const checkBoxComponents: ComponentCardItem[] = [
	{
		id: 'checkbox-01',
		component: Checkbox01Component,
		code: checkbox01Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-02',
		component: Checkbox02Component,
		code: checkbox02Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-03',
		component: Checkbox03Component,
		code: checkbox03Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-04',
		component: Checkbox04Component,
		code: checkbox04Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-05',
		component: Checkbox05Component,
		code: checkbox05Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-06',
		component: Checkbox06Component,
		code: checkbox06Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-18',
		component: Checkbox18Component,
		code: checkbox18Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-07',
		component: Checkbox07Component,
		code: checkbox07Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-08',
		component: Checkbox08Component,
		code: checkbox08Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-09',
		component: Checkbox09Component,
		code: checkbox09Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-12',
		component: Checkbox12Component,
		code: checkbox12Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-11',
		component: Checkbox11Component,
		code: checkbox11Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-13',
		component: Checkbox13Component,
		code: checkbox13Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-10',
		component: Checkbox10Component,
		code: checkbox10Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-14',
		component: Checkbox14Component,
		code: checkbox14Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-15',
		component: Checkbox15Component,
		code: checkbox15Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-16',
		component: Checkbox16Component,
		code: checkbox16Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-17',
		component: Checkbox17Component,
		code: checkbox17Code,
		colNumber: 4,
		itemStyle: 4,
	},

	{
		id: 'checkbox-19',
		component: Checkbox19Component,
		code: checkbox19Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-20',
		component: Checkbox20Component,
		code: checkbox20Code,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-21',
		component: Checkbox21Component,
		code: checkbox21Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'checkbox-22',
		component: Checkbox22Component,
		code: checkbox22Code,
		colNumber: 4,
		itemStyle: 4,
	},
];
