import {
	Checkbox01Component,
	Checkbox02Component,
	Checkbox03Component,
	Checkbox04Component,
	Checkbox05Component,
	Checkbox06Component,
	Checkbox07Component,
	Checkbox08Component,
	Checkbox09Component,
	Checkbox10Component,
	Checkbox11Component,
	Checkbox12Component,
	Checkbox13Component,
	Checkbox14Component,
	Checkbox15Component,
	Checkbox16Component,
	Checkbox17Component,
	Checkbox18Component,
	Checkbox19Component,
	Checkbox20Component,
	Checkbox21Component,
	Checkbox22Component,
} from '../components/checkbox';
import { ComponentCardItem } from '../core';

export const checkBoxComponents: ComponentCardItem[] = [
	{
		id: 'checkbox-01',
		component: Checkbox01Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-02',
		component: Checkbox02Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-03',
		component: Checkbox03Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-04',
		component: Checkbox04Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-05',
		component: Checkbox05Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-06',
		component: Checkbox06Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-18',
		component: Checkbox18Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-07',
		component: Checkbox07Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-08',
		component: Checkbox08Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-09',
		component: Checkbox09Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-12',
		component: Checkbox12Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-11',
		component: Checkbox11Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-13',
		component: Checkbox13Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-10',
		component: Checkbox10Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-14',
		component: Checkbox14Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-15',
		component: Checkbox15Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-16',
		component: Checkbox16Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-17',
		component: Checkbox17Component,
		colNumber: 4,
		itemStyle: 4,
	},

	{
		id: 'checkbox-19',
		component: Checkbox19Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-20',
		component: Checkbox20Component,
		colNumber: 4,
		itemStyle: 4,
	},
	{
		id: 'checkbox-21',
		component: Checkbox21Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'checkbox-22',
		component: Checkbox22Component,
		colNumber: 4,
		itemStyle: 4,
	},
];
