import {
	dialog01Code,
	Dialog01Component,
	dialog02Code,
	Dialog02Component,
	dialog03Code,
	Dialog03Component,
	dialog04Code,
	Dialog04Component,
	dialog05Code,
	Dialog05Component,
	dialog06Code,
	Dialog06Component,
	dialog07Code,
	Dialog07Component,
	dialog08Code,
	Dialog08Component,
	dialog09Code,
	Dialog09Component,
	dialog10Code,
	Dialog10Component,
	dialog11Code,
	Dialog11Component,
	dialog12Code,
	Dialog12Component,
	dialog13Code,
	Dialog13Component,
	dialog14Code,
	Dialog14Component,
	dialog15Code,
	Dialog15Component,
	dialog16Code,
	Dialog16Component,
	dialog17Code,
	Dialog17Component,
	dialog18Code,
	Dialog18Component,
	dialog19Code,
	Dialog19Component,
	dialog20Code,
	Dialog20Component,
	dialog21Code,
	Dialog21Component,
	dialog22Code,
	Dialog22Component,
	dialog23Code,
	Dialog23Component,
	dialog24Code,
	Dialog24Component,
	dialog25Code,
	Dialog25Component,
	dialog26Code,
	Dialog26Component,
	dialog27Code,
	Dialog27Component,
	dialog28Code,
	Dialog28Component,
	dialog29Code,
	Dialog29Component,
	dialog30Code,
	Dialog30Component,
	dialog31Code,
	Dialog31Component,
} from '../components/dialog';
import { ComponentCardItem } from '../core';

export const dialogComponents: ComponentCardItem[] = [
	{
		id: 'dialog-01',
		component: Dialog01Component,
		code: dialog01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-02',
		component: Dialog02Component,
		code: dialog02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-03',
		component: Dialog03Component,
		code: dialog03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-04',
		component: Dialog04Component,
		code: dialog04Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-05',
		component: Dialog05Component,
		code: dialog05Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-06',
		component: Dialog06Component,
		code: dialog06Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-07',
		component: Dialog07Component,
		code: dialog07Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-08',
		component: Dialog08Component,
		code: dialog08Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-09',
		component: Dialog09Component,
		code: dialog09Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-10',
		component: Dialog10Component,
		code: dialog10Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-11',
		component: Dialog11Component,
		code: dialog11Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-12',
		component: Dialog12Component,
		code: dialog12Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-13',
		component: Dialog13Component,
		code: dialog13Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-14',
		component: Dialog14Component,
		code: dialog14Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-15',
		component: Dialog15Component,
		code: dialog15Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-16',
		component: Dialog16Component,
		code: dialog16Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-17',
		component: Dialog17Component,
		code: dialog17Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-18',
		component: Dialog18Component,
		code: dialog18Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-19',
		component: Dialog19Component,
		code: dialog19Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-20',
		component: Dialog20Component,
		code: dialog20Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-21',
		component: Dialog21Component,
		code: dialog21Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-22',
		component: Dialog22Component,
		code: dialog22Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-23',
		component: Dialog23Component,
		code: dialog23Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-24',
		component: Dialog24Component,
		code: dialog24Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-25',
		component: Dialog25Component,
		code: dialog25Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-26',
		component: Dialog26Component,
		code: dialog26Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-27',
		component: Dialog27Component,
		code: dialog27Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-28',
		component: Dialog28Component,
		code: dialog28Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-29',
		component: Dialog29Component,
		code: dialog29Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-30',
		component: Dialog30Component,
		code: dialog30Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-31',
		component: Dialog31Component,
		code: dialog31Code,
		colNumber: 4,
		itemStyle: 1,
	},
];
