import {
	Dialog01Component,
	Dialog02Component,
	Dialog03Component,
	Dialog04Component,
	Dialog05Component,
	Dialog06Component,
	Dialog07Component,
	Dialog08Component,
	Dialog09Component,
	Dialog10Component,
	Dialog11Component,
	Dialog12Component,
	Dialog13Component,
	Dialog14Component,
	Dialog15Component,
	Dialog16Component,
	Dialog17Component,
	Dialog18Component,
	Dialog19Component,
	Dialog20Component,
	Dialog21Component,
	Dialog22Component,
	Dialog23Component,
	Dialog24Component,
	Dialog25Component,
	Dialog26Component,
	Dialog27Component,
	Dialog28Component,
	Dialog29Component,
	Dialog30Component,
	Dialog31Component,
	Dialog32Component,
	Dialog33Component,
	Dialog34Component,
	Dialog35Component,
} from '../components/dialog';
import { ComponentCardItem } from '../core';

export const dialogComponents: ComponentCardItem[] = [
	{
		id: 'dialog-01',
		component: Dialog01Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-02',
		component: Dialog02Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-03',
		component: Dialog03Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-04',
		component: Dialog04Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-05',
		component: Dialog05Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-06',
		component: Dialog06Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-07',
		component: Dialog07Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-08',
		component: Dialog08Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-09',
		component: Dialog09Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-34',
		component: Dialog34Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-10',
		component: Dialog10Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-11',
		component: Dialog11Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-12',
		component: Dialog12Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-13',
		component: Dialog13Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-14',
		component: Dialog14Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-15',
		component: Dialog15Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-16',
		component: Dialog16Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-17',
		component: Dialog17Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-18',
		component: Dialog18Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-19',
		component: Dialog19Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-20',
		component: Dialog20Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-21',
		component: Dialog21Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-22',
		component: Dialog22Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-23',
		component: Dialog23Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-24',
		component: Dialog24Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-25',
		component: Dialog25Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-26',
		component: Dialog26Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-27',
		component: Dialog27Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-28',
		component: Dialog28Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-29',
		component: Dialog29Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-30',
		component: Dialog30Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-31',
		component: Dialog31Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-32',
		component: Dialog32Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-33',
		component: Dialog33Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-35',
		component: Dialog35Component,
		colNumber: 4,
		itemStyle: 1,
	},
];
