import {
	dialog01Code,
	Dialog01Component,
	dialog02Code,
	Dialog02Component,
	dialog03Code,
	Dialog03Component,
	dialog04Code,
	Dialog04Component,
	dialog05Code,
	Dialog05Component,
	dialog06Code,
	Dialog06Component,
	dialog07Code,
	Dialog07Component,
	dialog08Code,
	Dialog08Component,
	dialog09Code,
	Dialog09Component,
} from '../components/dialog';
import { ComponentCardItem } from '../core';

export const dialogComponents: ComponentCardItem[] = [
	{
		id: 'dialog-01',
		component: Dialog01Component,
		code: dialog01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-02',
		component: Dialog02Component,
		code: dialog02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-03',
		component: Dialog03Component,
		code: dialog03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-04',
		component: Dialog04Component,
		code: dialog04Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-05',
		component: Dialog05Component,
		code: dialog05Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-06',
		component: Dialog06Component,
		code: dialog06Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-07',
		component: Dialog07Component,
		code: dialog07Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-08',
		component: Dialog08Component,
		code: dialog08Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'dialog-09',
		component: Dialog09Component,
		code: dialog09Code,
		colNumber: 4,
		itemStyle: 1,
	},
];
