import {
	dropdown01Code,
	Dropdown01Component,
	dropdown02Code,
	Dropdown02Component,
	dropdown03Code,
	Dropdown03Component,
	dropdown04Code,
	Dropdown04Component,
	dropdown05Code,
	Dropdown05Component,
	dropdown06Code,
	Dropdown06Component,
	dropdown07Code,
	Dropdown07Component,
	dropdown08Code,
	Dropdown08Component,
	dropdown09Code,
	Dropdown09Component,
} from '../components/dropdown';
import { ComponentCardItem } from '../core';

export const dropdownComponents: ComponentCardItem[] = [
	{
		component: Dropdown01Component,
		code: dropdown01Code,
		id: 'dropdown-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown02Component,
		code: dropdown02Code,
		id: 'dropdown-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown03Component,
		code: dropdown03Code,
		id: 'dropdown-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown04Component,
		code: dropdown04Code,
		id: 'dropdown-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown05Component,
		code: dropdown05Code,
		id: 'dropdown-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown06Component,
		code: dropdown06Code,
		id: 'dropdown-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown07Component,
		code: dropdown07Code,
		id: 'dropdown-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown08Component,
		code: dropdown08Code,
		id: 'dropdown-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown09Component,
		code: dropdown09Code,
		id: 'dropdown-09',
		colNumber: 4,
		itemStyle: 1,
	},
];
