import {
	Dropdown01Component,
	Dropdown02Component,
	Dropdown03Component,
	Dropdown04Component,
	Dropdown05Component,
	Dropdown06Component,
	Dropdown07Component,
	Dropdown08Component,
	Dropdown09Component,
	Dropdown10Component,
	Dropdown11Component,
	Dropdown12Component,
	Dropdown13Component,
	Dropdown14Component,
	Dropdown15Component,
	Dropdown16Component,
} from '../components/dropdown';
import { ComponentCardItem } from '../core';

export const dropdownComponents: ComponentCardItem[] = [
	{
		component: Dropdown01Component,
		id: 'dropdown-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown02Component,
		id: 'dropdown-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown03Component,
		id: 'dropdown-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown04Component,
		id: 'dropdown-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown05Component,
		id: 'dropdown-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown06Component,
		id: 'dropdown-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown07Component,
		id: 'dropdown-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown08Component,
		id: 'dropdown-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown09Component,
		id: 'dropdown-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown10Component,
		id: 'dropdown-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown11Component,
		id: 'dropdown-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown12Component,
		id: 'dropdown-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown16Component,
		id: 'dropdown-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown13Component,
		id: 'dropdown-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown14Component,
		id: 'dropdown-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Dropdown15Component,
		id: 'dropdown-15',
		colNumber: 4,
		itemStyle: 1,
	},
];
