import {
	fileUpload01Code,
	FileUpload01Component,
	fileUpload02Code,
	FileUpload02Component,
	fileUpload03Code,
	FileUpload03Component,
	fileUpload04Code,
	FileUpload04Component,
	fileUpload05Code,
	FileUpload05Component,
	fileUpload06Code,
	FileUpload06Component,
	fileUpload07Code,
	FileUpload07Component,
	fileUpload08Code,
	FileUpload08Component,
	fileUpload09Code,
	FileUpload09Component,
} from '../components/file-upload';
import { ComponentCardItem } from '../core';

export const fileUploadComponents: ComponentCardItem[] = [
	{
		id: 'file-upload-01',
		component: FileUpload01Component,
		code: fileUpload01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'file-upload-02',
		component: FileUpload02Component,
		code: fileUpload02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'file-upload-03',
		component: FileUpload03Component,
		code: fileUpload03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'file-upload-04',
		component: FileUpload04Component,
		code: fileUpload04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'file-upload-05',
		component: FileUpload05Component,
		code: fileUpload05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'file-upload-06',
		component: FileUpload06Component,
		code: fileUpload06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'file-upload-07',
		component: FileUpload07Component,
		code: fileUpload07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'file-upload-08',
		component: FileUpload08Component,
		code: fileUpload08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'file-upload-09',
		component: FileUpload09Component,
		code: fileUpload09Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
