import {
	input01Code,
	Input01Component,
	input02Code,
	Input02Component,
	input03Code,
	Input03Component,
	input04Code,
	Input04Component,
	input05Code,
	Input05Component,
	input06Code,
	Input06Component,
	input07Code,
	Input07Component,
	input08Code,
	Input08Component,
	input09Code,
	Input09Component,
	input10Code,
	Input10Component,
	input11Code,
	Input11Component,
	input12Code,
	Input12Component,
	input13Code,
	Input13Component,
	input14Code,
	Input14Component,
	input15Code,
	Input15Component,
	input16Code,
	Input16Component,
	input17Code,
	Input17Component,
	input18Code,
	Input18Component,
	input19Code,
	Input19Component,
	input20Code,
	Input20Component,
} from '../components/input';
import { ComponentCardItem } from '../core';

export const inputComponents: ComponentCardItem[] = [
	{
		component: Input01Component,
		code: input01Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-01',
	},
	{
		component: Input02Component,
		code: input02Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-02',
	},
	{
		component: Input03Component,
		code: input03Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-03',
	},
	{
		component: Input04Component,
		code: input04Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-04',
	},
	{
		component: Input05Component,
		code: input05Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-05',
	},
	{
		component: Input06Component,
		code: input06Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-06',
	},
	{
		component: Input07Component,
		code: input07Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-07',
	},
	{
		component: Input08Component,
		code: input08Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-08',
	},
	{
		component: Input09Component,
		code: input09Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-09',
	},
	{
		component: Input10Component,
		code: input10Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-10',
	},
	{
		component: Input11Component,
		code: input11Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-11',
	},
	{
		component: Input12Component,
		code: input12Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-12',
	},
	{
		component: Input13Component,
		code: input13Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-13',
	},
	{
		component: Input14Component,
		code: input14Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-14',
	},
	{
		component: Input15Component,
		code: input15Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-15',
	},
	{
		component: Input16Component,
		code: input16Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-16',
	},
	{
		component: Input17Component,
		code: input17Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-17',
	},
	{
		component: Input18Component,
		code: input18Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-18',
	},
	{
		component: Input19Component,
		code: input19Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-19',
	},
	{
		component: Input20Component,
		code: input20Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-20',
	},
];
