import {
	input01Code,
	Input01Component,
	input02Code,
	Input02Component,
	input03Code,
	Input03Component,
	input04Code,
	Input04Component,
	input05Code,
	Input05Component,
	input06Code,
	Input06Component,
	input07Code,
	Input07Component,
	input08Code,
	Input08Component,
	input09Code,
	Input09Component,
	input10Code,
	Input10Component,
	input11Code,
	Input11Component,
	input12Code,
	Input12Component,
	input13Code,
	Input13Component,
	input14Code,
	Input14Component,
	input15Code,
	Input15Component,
	input16Code,
	Input16Component,
	input17Code,
	Input17Component,
	input18Code,
	Input18Component,
	input19Code,
	Input19Component,
	input20Code,
	Input20Component,
	input21Code,
	Input21Component,
	input22Code,
	Input22Component,
	input23Code,
	Input23Component,
	input24Code,
	Input24Component,
	input25Code,
	Input25Component,
	input26Code,
	Input26Component,
	input27Code,
	Input27Component,
	input28Code,
	Input28Component,
	input29Code,
	Input29Component,
	input30Code,
	Input30Component,
	input31Code,
	Input31Component,
	input32Code,
	Input32Component,
	input33Code,
	Input33Component,
	input34Code,
	Input34Component,
	input35Code,
	Input35Component,
	input36Code,
	Input36Component,
	input37Code,
	Input37Component,
	input38Code,
	Input38Component,
	input39Code,
	Input39Component,
	input40Code,
	Input40Component,
	input41Code,
	Input41Component,
	input42Code,
	Input42Component,
	input43Code,
	Input43Component,
	input44Code,
	Input44Component,
	input45Code,
	Input45Component,
	input46Code,
	Input46Component,
	input47Code,
	Input47Component,
} from '../components/input';
import { ComponentCardItem } from '../core';

export const inputComponents: ComponentCardItem[] = [
	{
		component: Input01Component,
		code: input01Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-01',
	},
	{
		component: Input02Component,
		code: input02Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-02',
	},
	{
		component: Input03Component,
		code: input03Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-03',
	},
	{
		component: Input04Component,
		code: input04Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-04',
	},
	{
		component: Input05Component,
		code: input05Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-05',
	},
	{
		component: Input06Component,
		code: input06Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-06',
	},
	{
		component: Input07Component,
		code: input07Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-07',
	},
	{
		component: Input08Component,
		code: input08Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-08',
	},
	{
		component: Input09Component,
		code: input09Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-09',
	},
	{
		component: Input10Component,
		code: input10Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-10',
	},
	{
		component: Input11Component,
		code: input11Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-11',
	},
	{
		component: Input12Component,
		code: input12Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-12',
	},
	{
		component: Input13Component,
		code: input13Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-13',
	},
	{
		component: Input14Component,
		code: input14Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-14',
	},
	{
		component: Input15Component,
		code: input15Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-15',
	},
	{
		component: Input16Component,
		code: input16Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-16',
	},
	{
		component: Input17Component,
		code: input17Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-17',
	},
	{
		component: Input18Component,
		code: input18Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-18',
	},
	{
		component: Input19Component,
		code: input19Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-19',
	},
	{
		component: Input20Component,
		code: input20Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-20',
	},
	{
		component: Input21Component,
		code: input21Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-21',
	},
	{
		component: Input22Component,
		code: input22Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-22',
	},
	{
		component: Input23Component,
		code: input23Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-23',
	},
	{
		component: Input24Component,
		code: input24Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-24',
	},
	{
		component: Input25Component,
		code: input25Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-25',
	},
	{
		component: Input26Component,
		code: input26Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-26',
	},
	{
		component: Input27Component,
		code: input27Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-27',
	},
	{
		component: Input28Component,
		code: input28Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-28',
	},
	{
		component: Input29Component,
		code: input29Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-29',
	},
	{
		component: Input30Component,
		code: input30Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-30',
	},
	{
		component: Input31Component,
		code: input31Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-31',
	},
	{
		component: Input32Component,
		code: input32Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-32',
	},
	{
		component: Input33Component,
		code: input33Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-33',
	},
	{
		component: Input34Component,
		code: input34Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-34',
	},
	{
		component: Input35Component,
		code: input35Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-35',
	},
	{
		component: Input36Component,
		code: input36Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-36',
	},
	{
		component: Input37Component,
		code: input37Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-37',
	},
	{
		component: Input38Component,
		code: input38Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-38',
	},
	{
		component: Input39Component,
		code: input39Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-39',
	},
	{
		component: Input40Component,
		code: input40Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-40',
	},
	{
		component: Input41Component,
		code: input41Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-41',
	},
	{
		component: Input42Component,
		code: input42Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-42',
	},
	{
		component: Input43Component,
		code: input43Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-43',
	},
	{
		component: Input44Component,
		code: input44Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-44',
	},
	{
		component: Input45Component,
		code: input45Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-45',
	},
	{
		component: Input46Component,
		code: input46Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-46',
	},
	{
		component: Input47Component,
		code: input47Code,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-47',
	},
];
