import {
	Input01Component,
	Input02Component,
	Input03Component,
	Input04Component,
	Input05Component,
	Input06Component,
	Input07Component,
	Input08Component,
	Input09Component,
	Input10Component,
	Input11Component,
	Input12Component,
	Input13Component,
	Input14Component,
	Input15Component,
	Input16Component,
	Input17Component,
	Input18Component,
	Input19Component,
	Input20Component,
	Input21Component,
	Input22Component,
	Input23Component,
	Input24Component,
	Input25Component,
	Input26Component,
	Input27Component,
	Input28Component,
	Input29Component,
	Input30Component,
	Input31Component,
	Input32Component,
	Input33Component,
	Input34Component,
	Input35Component,
	Input36Component,
	Input37Component,
	Input38Component,
	Input39Component,
	Input40Component,
	Input41Component,
	Input42Component,
	Input43Component,
	Input44Component,
	Input45Component,
	Input46Component,
	Input47Component,
	Input48Component,
	Input49Component,
	Input50Component,
	Input51Component,
	Input52Component,
	Input53Component,
	Input54Component,
	Input55Component,
} from '../components/input';
import { ComponentCardItem } from '../core';

export const inputComponents: ComponentCardItem[] = [
	{
		component: Input01Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-01',
	},
	{
		component: Input02Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-02',
	},
	{
		component: Input03Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-03',
	},
	{
		component: Input04Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-04',
	},
	{
		component: Input05Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-05',
	},
	{
		component: Input06Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-06',
	},
	{
		component: Input07Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-07',
	},
	{
		component: Input08Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-08',
	},
	{
		component: Input09Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-09',
	},
	{
		component: Input10Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-10',
	},
	{
		component: Input11Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-11',
	},
	{
		component: Input12Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-12',
	},
	{
		component: Input13Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-13',
	},
	{
		component: Input14Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-14',
	},
	{
		component: Input15Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-15',
	},
	{
		component: Input16Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-16',
	},
	{
		component: Input17Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-17',
	},
	{
		component: Input18Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-18',
	},
	{
		component: Input19Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-19',
	},
	{
		component: Input20Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-20',
	},
	{
		component: Input21Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-21',
	},
	{
		component: Input22Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-22',
	},
	{
		component: Input23Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-23',
	},
	{
		component: Input24Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-24',
	},
	{
		component: Input25Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-25',
	},
	{
		component: Input26Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-26',
	},
	{
		component: Input27Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-27',
	},
	{
		component: Input28Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-28',
	},
	{
		component: Input29Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-29',
	},
	{
		component: Input30Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-30',
	},
	{
		component: Input31Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-31',
	},
	{
		component: Input32Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-32',
	},
	{
		component: Input33Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-33',
	},
	{
		component: Input34Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-34',
	},
	{
		component: Input35Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-35',
	},
	{
		component: Input36Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-36',
	},
	{
		component: Input37Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-37',
	},
	{
		component: Input38Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-38',
	},
	{
		component: Input39Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-39',
	},
	{
		component: Input40Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-40',
	},
	{
		component: Input41Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-41',
	},
	{
		component: Input42Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-42',
	},
	{
		component: Input43Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-43',
	},
	{
		component: Input44Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-44',
	},
	{
		component: Input45Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-45',
	},
	{
		component: Input46Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-46',
	},
	{
		component: Input47Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-47',
	},
	{
		component: Input48Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-48',
	},
	{
		component: Input49Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-49',
	},
	{
		component: Input50Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-50',
	},
	{
		component: Input51Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-51',
	},
	{
		component: Input52Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-52',
	},
	{
		component: Input53Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-53',
	},
	{
		component: Input54Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-54',
	},
	{
		component: Input55Component,
		colNumber: 4,
		itemStyle: 1,
		id: 'input-55',
	},
];
