import {
	Notification01Component,
	Notification02Component,
	Notification03Component,
	Notification04Component,
	Notification05Component,
	Notification06Component,
	Notification07Component,
	Notification08Component,
	Notification09Component,
	Notification10Component,
	Notification11Component,
	Notification12Component,
	Notification13Component,
	Notification14Component,
	Notification15Component,
	Notification16Component,
	Notification17Component,
	Notification18Component,
	Notification19Component,
	Notification20Component,
	Notification21Component,
	Notification22Component,
	Notification23Component,
	Notification24Component,
	Notification25Component,
	Notification26Component,
	Notification27Component,
	Notification28Component,
	Notification29Component,
	Notification30Component,
	Notification31Component,
	Notification32Component,
	Notification33Component,
} from '../components/notification';
import { ComponentCardItem } from '../core';

export const notificationComponents: ComponentCardItem[] = [
	{
		id: 'notification-27',
		component: Notification27Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-28',
		component: Notification28Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-29',
		component: Notification29Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-30',
		component: Notification30Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-31',
		component: Notification31Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-32',
		component: Notification32Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-33',
		component: Notification33Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-01',
		component: Notification01Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-02',
		component: Notification02Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-03',
		component: Notification03Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-04',
		component: Notification04Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-05',
		component: Notification05Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-06',
		component: Notification06Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-07',
		component: Notification07Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-08',
		component: Notification08Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-09',
		component: Notification09Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-10',
		component: Notification10Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-11',
		component: Notification11Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-12',
		component: Notification12Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-13',
		component: Notification13Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-14',
		component: Notification14Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-15',
		component: Notification15Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-16',
		component: Notification16Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-22',
		component: Notification22Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-23',
		component: Notification23Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-17',
		component: Notification17Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-18',
		component: Notification18Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-19',
		component: Notification19Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-20',
		component: Notification20Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-21',
		component: Notification21Component,
		colNumber: 2,
		itemStyle: 1,
	},

	{
		id: 'notification-24',
		component: Notification24Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-25',
		component: Notification25Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-26',
		component: Notification26Component,
		colNumber: 2,
		itemStyle: 1,
	},
];
