import {
	Notification01Component,
	Notification02Component,
	Notification03Component,
	Notification04Component,
	Notification05Component,
	Notification06Component,
	Notification07Component,
	Notification08Component,
	Notification09Component,
	Notification10Component,
	Notification11Component,
	Notification12Component,
	Notification13Component,
	Notification14Component,
	Notification15Component,
	Notification16Component,
	Notification17Component,
	Notification18Component,
	Notification19Component,
	Notification20Component,
	Notification21Component,
	Notification22Component,
	Notification23Component,
	Notification24Component,
	Notification25Component,
	Notification26Component,
	Notification27Component,
	Notification28Component,
	Notification29Component,
	Notification30Component,
	Notification31Component,
	Notification32Component,
	Notification33Component,
	notification01Code,
	notification02Code,
	notification03Code,
	notification04Code,
	notification05Code,
	notification06Code,
	notification07Code,
	notification08Code,
	notification09Code,
	notification10Code,
	notification11Code,
	notification12Code,
	notification13Code,
	notification14Code,
	notification15Code,
	notification16Code,
	notification17Code,
	notification18Code,
	notification19Code,
	notification20Code,
	notification21Code,
	notification22Code,
	notification23Code,
	notification24Code,
	notification25Code,
	notification26Code,
	notification27Code,
	notification28Code,
	notification29Code,
	notification30Code,
	notification31Code,
	notification32Code,
	notification33Code,
} from '../components/notification';
import { ComponentCardItem } from '../core';

export const notificationComponents: ComponentCardItem[] = [
	{
		id: 'notification-27',
		component: Notification27Component,
		code: notification27Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-28',
		component: Notification28Component,
		code: notification28Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-29',
		component: Notification29Component,
		code: notification29Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-30',
		component: Notification30Component,
		code: notification30Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-31',
		component: Notification31Component,
		code: notification31Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-32',
		component: Notification32Component,
		code: notification32Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-33',
		component: Notification33Component,
		code: notification33Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-01',
		component: Notification01Component,
		code: notification01Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-02',
		component: Notification02Component,
		code: notification02Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-03',
		component: Notification03Component,
		code: notification03Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-04',
		component: Notification04Component,
		code: notification04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-05',
		component: Notification05Component,
		code: notification05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-06',
		component: Notification06Component,
		code: notification06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-07',
		component: Notification07Component,
		code: notification07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-08',
		component: Notification08Component,
		code: notification08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-09',
		component: Notification09Component,
		code: notification09Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-10',
		component: Notification10Component,
		code: notification10Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-11',
		component: Notification11Component,
		code: notification11Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-12',
		component: Notification12Component,
		code: notification12Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-13',
		component: Notification13Component,
		code: notification13Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-14',
		component: Notification14Component,
		code: notification14Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-15',
		component: Notification15Component,
		code: notification15Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-16',
		component: Notification16Component,
		code: notification16Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-22',
		component: Notification22Component,
		code: notification22Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-23',
		component: Notification23Component,
		code: notification23Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-17',
		component: Notification17Component,
		code: notification17Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-18',
		component: Notification18Component,
		code: notification18Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-19',
		component: Notification19Component,
		code: notification19Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-20',
		component: Notification20Component,
		code: notification20Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-21',
		component: Notification21Component,
		code: notification21Code,
		colNumber: 2,
		itemStyle: 1,
	},

	{
		id: 'notification-24',
		component: Notification24Component,
		code: notification24Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-25',
		component: Notification25Component,
		code: notification25Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'notification-26',
		component: Notification26Component,
		code: notification26Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
