import {
	pagination01Code,
	Pagination01Component,
	pagination02Code,
	Pagination02Component,
	pagination03Code,
	Pagination03Component,
	pagination04Code,
	Pagination04Component,
	pagination05Code,
	Pagination05Component,
	pagination06Code,
	Pagination06Component,
	pagination07Code,
	Pagination07Component,
	pagination08Code,
	Pagination08Component,
	pagination09Code,
	Pagination09Component,
	pagination10Code,
	Pagination10Component,
	pagination11Code,
	Pagination11Component,
	pagination12Code,
	Pagination12Component,
} from '../components/pagination';
import { ComponentCardItem } from '../core';

export const paginationComponents: ComponentCardItem[] = [
	{
		id: 'pagination-01',
		component: Pagination01Component,
		code: pagination01Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-02',
		component: Pagination02Component,
		code: pagination02Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-03',
		component: Pagination03Component,
		code: pagination03Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-04',
		component: Pagination04Component,
		code: pagination04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-05',
		component: Pagination05Component,
		code: pagination05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-06',
		component: Pagination06Component,
		code: pagination06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-07',
		component: Pagination07Component,
		code: pagination07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-08',
		component: Pagination08Component,
		code: pagination08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-09',
		component: Pagination09Component,
		code: pagination09Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-10',
		component: Pagination10Component,
		code: pagination10Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-11',
		component: Pagination11Component,
		code: pagination11Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'pagination-12',
		component: Pagination12Component,
		code: pagination12Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
