import {
	Popover01Code,
	Popover01Component,
	Popover02Code,
	Popover02Component,
	Popover03Code,
	Popover03Component,
	Popover04Code,
	Popover04Component,
	Popover05Code,
	Popover05Component,
	Popover06Code,
	Popover06Component,
	Popover07Code,
	Popover07Component,
	Popover08Code,
	Popover08Component,
	Popover09Code,
	Popover09Component,
	Popover10Code,
	Popover10Component,
	Popover11Code,
	Popover11Component,
} from '@/app/components/popover';
import { ComponentCardItem } from '../core';

export const popoverComponents: ComponentCardItem[] = [
	{
		id: 'popover-01',
		component: Popover01Component,
		code: Popover01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-02',
		component: Popover02Component,
		code: Popover02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-03',
		component: Popover03Component,
		code: Popover03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-04',
		component: Popover04Component,
		code: Popover04Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-05',
		component: Popover05Component,
		code: Popover05Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-06',
		component: Popover06Component,
		code: Popover06Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-11',
		component: Popover11Component,
		code: Popover11Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-07',
		component: Popover07Component,
		code: Popover07Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-08',
		component: Popover08Component,
		code: Popover08Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-09',
		component: Popover09Component,
		code: Popover09Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-10',
		component: Popover10Component,
		code: Popover10Code,
		colNumber: 4,
		itemStyle: 1,
	},
];
