import {
	popover01Code,
	Popover01Component,
	popover02Code,
	Popover02Component,
	popover03Code,
	Popover03Component,
	popover04Code,
	Popover04Component,
	popover05Code,
	Popover05Component,
	popover06Code,
	Popover06Component,
	popover07Code,
	Popover07Component,
	popover08Code,
	Popover08Component,
	popover09Code,
	Popover09Component,
	popover10Code,
	Popover10Component,
	popover11Code,
	Popover11Component,
} from '@/app/components/popover';
import { ComponentCardItem } from '../core';

export const popoverComponents: ComponentCardItem[] = [
	{
		id: 'popover-01',
		component: Popover01Component,
		code: popover01Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-02',
		component: Popover02Component,
		code: popover02Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-03',
		component: Popover03Component,
		code: popover03Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-04',
		component: Popover04Component,
		code: popover04Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-05',
		component: Popover05Component,
		code: popover05Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-06',
		component: Popover06Component,
		code: popover06Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-11',
		component: Popover11Component,
		code: popover11Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-07',
		component: Popover07Component,
		code: popover07Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-08',
		component: Popover08Component,
		code: popover08Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-09',
		component: Popover09Component,
		code: popover09Code,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'popover-10',
		component: Popover10Component,
		code: popover10Code,
		colNumber: 4,
		itemStyle: 1,
	},
];
