import {
	Radio01Component,
	Radio02Component,
	Radio03Component,
	Radio04Component,
	Radio05Component,
	Radio06Component,
	Radio07Component,
	Radio08Component,
	Radio09Component,
	Radio10Component,
	Radio11Component,
	Radio12Component,
	Radio13Component,
	Radio14Component,
	Radio15Component,
	Radio16Component,
	Radio17Component,
	Radio18Component,
	Radio19Component,
	Radio20Component,
} from '../components/radio';
import { ComponentCardItem } from '../core';

export const radioComponents: ComponentCardItem[] = [
	{
		component: Radio01Component,
		id: 'radio-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio02Component,
		id: 'radio-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio03Component,
		id: 'radio-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio04Component,
		id: 'radio-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio05Component,
		id: 'radio-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio06Component,
		id: 'radio-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio07Component,
		id: 'radio-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio08Component,
		id: 'radio-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio09Component,
		id: 'radio-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio10Component,
		id: 'radio-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio11Component,
		id: 'radio-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio12Component,
		id: 'radio-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio13Component,
		id: 'radio-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio14Component,
		id: 'radio-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio15Component,
		id: 'radio-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio16Component,
		id: 'radio-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio17Component,
		id: 'radio-17',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio18Component,
		id: 'radio-18',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio19Component,
		id: 'radio-19',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio20Component,
		id: 'radio-20',
		colNumber: 4,
		itemStyle: 1,
	},
];
