import {
	radio01Code,
	Radio01Component,
	radio02Code,
	Radio02Component,
	radio03Code,
	Radio03Component,
	radio04Code,
	Radio04Component,
	radio05Code,
	Radio05Component,
	radio06Code,
	Radio06Component,
	radio07Code,
	Radio07Component,
	radio08Code,
	Radio08Component,
	radio09Code,
	Radio09Component,
	radio10Code,
	Radio10Component,
	radio11Code,
	Radio11Component,
	radio12Code,
	Radio12Component,
	radio13Code,
	Radio13Component,
	radio14Code,
	Radio14Component,
	radio15Code,
	Radio15Component,
	radio16Code,
	Radio16Component,
	radio17Code,
	Radio17Component,
	radio18Code,
	Radio18Component,
	radio19Code,
	Radio19Component,
	radio20Code,
	Radio20Component,
} from '../components/radio';
import { ComponentCardItem } from '../core';

export const radioComponents: ComponentCardItem[] = [
	{
		component: Radio01Component,
		code: radio01Code,
		id: 'radio-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio02Component,
		code: radio02Code,
		id: 'radio-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio03Component,
		code: radio03Code,
		id: 'radio-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio04Component,
		code: radio04Code,
		id: 'radio-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio05Component,
		code: radio05Code,
		id: 'radio-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio06Component,
		code: radio06Code,
		id: 'radio-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio07Component,
		code: radio07Code,
		id: 'radio-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio08Component,
		code: radio08Code,
		id: 'radio-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio09Component,
		code: radio09Code,
		id: 'radio-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio10Component,
		code: radio10Code,
		id: 'radio-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio11Component,
		code: radio11Code,
		id: 'radio-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio12Component,
		code: radio12Code,
		id: 'radio-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio13Component,
		code: radio13Code,
		id: 'radio-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio14Component,
		code: radio14Code,
		id: 'radio-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio15Component,
		code: radio15Code,
		id: 'radio-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio16Component,
		code: radio16Code,
		id: 'radio-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio17Component,
		code: radio17Code,
		id: 'radio-17',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio18Component,
		code: radio18Code,
		id: 'radio-18',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio19Component,
		code: radio19Code,
		id: 'radio-19',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Radio20Component,
		code: radio20Code,
		id: 'radio-20',
		colNumber: 4,
		itemStyle: 1,
	},
];
