import {
	Select01Component,
	Select02Component,
	Select03Component,
	Select04Component,
	Select05Component,
	Select06Component,
	Select07Component,
	Select08Component,
	Select09Component,
	Select10Component,
	Select11Component,
	Select12Component,
	Select13Component,
	Select14Component,
	Select15Component,
	Select16Component,
	Select17Component,
	Select18Component,
	Select19Component,
	Select20Component,
	Select21Component,
	Select22Component,
	Select23Component,
	Select24Component,
	Select25Component,
	Select26Component,
	Select27Component,
	Select28Component,
	Select29Component,
	Select30Component,
	Select31Component,
	Select32Component,
	Select33Component,
	Select34Component,
	Select35Component,
	Select36Component,
	Select37Component,
	Select38Component,
	Select39Component,
	Select40Component,
	Select41Component,
} from '../components/select';
import { ComponentCardItem } from '../core';

export const selectComponents: ComponentCardItem[] = [
	{
		id: 'select-01',
		component: Select01Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-02',
		component: Select02Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-03',
		component: Select03Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-04',
		component: Select04Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-05',
		component: Select05Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-06',
		component: Select06Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-07',
		component: Select07Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-08',
		component: Select08Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-09',
		component: Select09Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-10',
		component: Select10Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-11',
		component: Select11Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-12',
		component: Select12Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-13',
		component: Select13Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-14',
		component: Select14Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-15',
		component: Select15Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-16',
		component: Select16Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-17',
		component: Select17Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-18',
		component: Select18Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-19',
		component: Select19Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-20',
		component: Select20Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-21',
		component: Select21Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-22',
		component: Select22Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-23',
		component: Select23Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-24',
		component: Select24Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-25',
		component: Select25Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-26',
		component: Select26Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-27',
		component: Select27Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-28',
		component: Select28Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-40',
		component: Select40Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-41',
		component: Select41Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-29',
		component: Select29Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-30',
		component: Select30Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-31',
		component: Select31Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-32',
		component: Select32Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-33',
		component: Select33Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-34',
		component: Select34Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-35',
		component: Select35Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-36',
		component: Select36Component,
		colNumber: 4,
		itemStyle: 1,
	},
	{
		id: 'select-37',
		component: Select37Component,
		colNumber: 4,
		itemStyle: 1,
	},
	// {
	// 	id: 'select-38',
	// 	component: Select38Component,
	// 	colNumber: 4,
	// 	itemStyle: 1,
	// },
	// {
	// 	id: 'select-39',
	// 	component: Select39Component,
	// 	colNumber: 4,
	// 	itemStyle: 1,
	// },
];
