import {
	Slider01Component,
	Slider02Component,
	Slider03Component,
	Slider04Component,
	Slider05Component,
	Slider06Component,
	Slider07Component,
	Slider08Component,
	Slider09Component,
	Slider10Component,
	Slider11Component,
	Slider12Component,
	Slider13Component,
	Slider14Component,
	Slider15Component,
	Slider16Component,
	Slider17Component,
	Slider18Component,
	Slider19Component,
} from '../components/slider';
import { ComponentCardItem } from '../core';

export const sliderComponents: ComponentCardItem[] = [
	{
		component: Slider01Component,
		id: 'slider-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider02Component,
		id: 'slider-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider03Component,
		id: 'slider-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider04Component,
		id: 'slider-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider05Component,
		id: 'slider-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider06Component,
		id: 'slider-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider07Component,
		id: 'slider-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider08Component,
		id: 'slider-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider09Component,
		id: 'slider-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider19Component,
		id: 'slider-19',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider10Component,
		id: 'slider-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider11Component,
		id: 'slider-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider12Component,
		id: 'slider-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider13Component,
		id: 'slider-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider14Component,
		id: 'slider-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider15Component,
		id: 'slider-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider16Component,
		id: 'slider-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider17Component,
		id: 'slider-17',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider18Component,
		id: 'slider-18',
		colNumber: 4,
		itemStyle: 1,
	},
];
