import {
	slider01Code,
	Slider01Component,
	slider02Code,
	Slider02Component,
	slider03Code,
	Slider03Component,
	slider04Code,
	Slider04Component,
	slider05Code,
	Slider05Component,
	slider06Code,
	Slider06Component,
	slider07Code,
	Slider07Component,
	slider08Code,
	Slider08Component,
	slider09Code,
	Slider09Component,
	slider10Code,
	Slider10Component,
	slider11Code,
	Slider11Component,
	slider12Code,
	Slider12Component,
	slider13Code,
	Slider13Component,
	slider14Code,
	Slider14Component,
	slider15Code,
	Slider15Component,
	slider16Code,
	Slider16Component,
	slider17Code,
	Slider17Component,
	slider18Code,
	Slider18Component,
	slider19Code,
	Slider19Component,
} from '../components/slider';
import { ComponentCardItem } from '../core';

export const sliderComponents: ComponentCardItem[] = [
	{
		component: Slider01Component,
		code: slider01Code,
		id: 'slider-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider02Component,
		code: slider02Code,
		id: 'slider-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider03Component,
		code: slider03Code,
		id: 'slider-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider04Component,
		code: slider04Code,
		id: 'slider-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider05Component,
		code: slider05Code,
		id: 'slider-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider06Component,
		code: slider06Code,
		id: 'slider-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider07Component,
		code: slider07Code,
		id: 'slider-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider08Component,
		code: slider08Code,
		id: 'slider-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider09Component,
		code: slider09Code,
		id: 'slider-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider19Component,
		code: slider19Code,
		id: 'slider-19',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider10Component,
		code: slider10Code,
		id: 'slider-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider11Component,
		code: slider11Code,
		id: 'slider-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider12Component,
		code: slider12Code,
		id: 'slider-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider13Component,
		code: slider13Code,
		id: 'slider-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider14Component,
		code: slider14Code,
		id: 'slider-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider15Component,
		code: slider15Code,
		id: 'slider-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider16Component,
		code: slider16Code,
		id: 'slider-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider17Component,
		code: slider17Code,
		id: 'slider-17',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Slider18Component,
		code: slider18Code,
		id: 'slider-18',
		colNumber: 4,
		itemStyle: 1,
	},
];
