import {
	Switch01Component,
	Switch02Component,
	Switch03Component,
	Switch04Component,
	Switch05Component,
	Switch06Component,
	Switch07Component,
	Switch08Component,
	Switch09Component,
	Switch10Component,
	Switch11Component,
	Switch12Component,
	Switch13Component,
	Switch14Component,
	Switch15Component,
	Switch16Component,
	Switch17Component,
	Switch18Component,
} from '../components/switch';
import { ComponentCardItem } from '../core';

export const switchComponents: ComponentCardItem[] = [
	{
		component: Switch01Component,
		id: 'switch-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch02Component,
		id: 'switch-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch03Component,
		id: 'switch-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch04Component,
		id: 'switch-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch05Component,
		id: 'switch-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch06Component,
		id: 'switch-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch07Component,
		id: 'switch-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch08Component,
		id: 'switch-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch09Component,
		id: 'switch-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch10Component,
		id: 'switch-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch11Component,
		id: 'switch-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch12Component,
		id: 'switch-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch13Component,
		id: 'switch-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch18Component,
		id: 'switch-18',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch14Component,
		id: 'switch-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch15Component,
		id: 'switch-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch16Component,
		id: 'switch-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch17Component,
		id: 'switch-17',
		colNumber: 4,
		itemStyle: 1,
	},
];
