import {
	switch01Code,
	Switch01Component,
	switch02Code,
	Switch02Component,
	switch03Code,
	Switch03Component,
	switch04Code,
	Switch04Component,
	switch05Code,
	Switch05Component,
	switch06Code,
	Switch06Component,
	switch07Code,
	Switch07Component,
	switch08Code,
	Switch08Component,
	switch09Code,
	Switch09Component,
	switch10Code,
	Switch10Component,
	switch11Code,
	Switch11Component,
	switch12Code,
	Switch12Component,
	switch13Code,
	Switch13Component,
	switch14Code,
	Switch14Component,
	switch15Code,
	Switch15Component,
	switch16Code,
	Switch16Component,
	switch17Code,
	Switch17Component,
	switch18Code,
	Switch18Component,
} from '../components/switch';
import { ComponentCardItem } from '../core';

export const switchComponents: ComponentCardItem[] = [
	{
		component: Switch01Component,
		code: switch01Code,
		id: 'switch-01',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch02Component,
		code: switch02Code,
		id: 'switch-02',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch03Component,
		code: switch03Code,
		id: 'switch-03',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch04Component,
		code: switch04Code,
		id: 'switch-04',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch05Component,
		code: switch05Code,
		id: 'switch-05',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch06Component,
		code: switch06Code,
		id: 'switch-06',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch07Component,
		code: switch07Code,
		id: 'switch-07',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch08Component,
		code: switch08Code,
		id: 'switch-08',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch09Component,
		code: switch09Code,
		id: 'switch-09',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch10Component,
		code: switch10Code,
		id: 'switch-10',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch11Component,
		code: switch11Code,
		id: 'switch-11',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch12Component,
		code: switch12Code,
		id: 'switch-12',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch13Component,
		code: switch13Code,
		id: 'switch-13',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch18Component,
		code: switch18Code,
		id: 'switch-18',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch14Component,
		code: switch14Code,
		id: 'switch-14',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch15Component,
		code: switch15Code,
		id: 'switch-15',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch16Component,
		code: switch16Code,
		id: 'switch-16',
		colNumber: 4,
		itemStyle: 1,
	},
	{
		component: Switch17Component,
		code: switch17Code,
		id: 'switch-17',
		colNumber: 4,
		itemStyle: 1,
	},
];
