import {
	tabs01Code,
	Tabs01Component,
	tabs02Code,
	Tabs02Component,
	tabs03Code,
	Tabs03Component,
	tabs04Code,
	Tabs04Component,
	tabs05Code,
	Tabs05Component,
	tabs06Code,
	Tabs06Component,
	tabs07Code,
	Tabs07Component,
	tabs08Code,
	Tabs08Component,
	tabs09Code,
	Tabs09Component,
	tabs10Code,
	Tabs10Component,
	tabs11Code,
	Tabs11Component,
	tabs12Code,
	Tabs12Component,
} from '../components/tabs';
import { ComponentCardItem } from '../core';

export const tabsComponents: ComponentCardItem[] = [
	{
		id: 'tabs-01',
		component: Tabs01Component,
		code: tabs01Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-02',
		component: Tabs02Component,
		code: tabs02Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-03',
		component: Tabs03Component,
		code: tabs03Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-04',
		component: Tabs04Component,
		code: tabs04Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-05',
		component: Tabs05Component,
		code: tabs05Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-06',
		component: Tabs06Component,
		code: tabs06Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-07',
		component: Tabs07Component,
		code: tabs07Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-08',
		component: Tabs08Component,
		code: tabs08Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-09',
		component: Tabs09Component,
		code: tabs09Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-10',
		component: Tabs10Component,
		code: tabs10Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-11',
		component: Tabs11Component,
		code: tabs11Code,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-12',
		component: Tabs12Component,
		code: tabs12Code,
		colNumber: 2,
		itemStyle: 1,
	},
];
