import {
	Tabs01Component,
	Tabs02Component,
	Tabs03Component,
	Tabs04Component,
	Tabs05Component,
	Tabs06Component,
	Tabs07Component,
	Tabs08Component,
	Tabs09Component,
	Tabs10Component,
	Tabs11Component,
	Tabs12Component,
	Tabs13Component,
	Tabs14Component,
	Tabs15Component,
	Tabs16Component,
	Tabs17Component,
	Tabs18Component,
	Tabs19Component,
	Tabs20Component,
} from '../components/tabs';
import { ComponentCardItem } from '../core';

export const tabsComponents: ComponentCardItem[] = [
	{
		id: 'tabs-01',
		component: Tabs01Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-02',
		component: Tabs02Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-03',
		component: Tabs03Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-04',
		component: Tabs04Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-05',
		component: Tabs05Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-06',
		component: Tabs06Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-07',
		component: Tabs07Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-08',
		component: Tabs08Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-09',
		component: Tabs09Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-10',
		component: Tabs10Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-11',
		component: Tabs11Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-12',
		component: Tabs12Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-13',
		component: Tabs13Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-14',
		component: Tabs14Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-15',
		component: Tabs15Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-16',
		component: Tabs16Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-17',
		component: Tabs17Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-18',
		component: Tabs18Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-19',
		component: Tabs19Component,
		colNumber: 2,
		itemStyle: 1,
	},
	{
		id: 'tabs-20',
		component: Tabs20Component,
		colNumber: 2,
		itemStyle: 1,
	},
];
