import { ThemePreset } from '../types';

export const MAX_HISTORY_SIZE = 50;
export const HISTORY_CLEANUP_THRESHOLD = 45;

export const DEFAULT_PRESET: ThemePreset = {
	label: 'Default',
	id: 'styles',
	source: 'BUILT_IN',
	styles: {
		light: {
			background: '#ffffff',
			foreground: '#0a0a0a',
			card: '#ffffff',
			'card-foreground': '#0a0a0a',
			popover: '#ffffff',
			'popover-foreground': '#0a0a0a',
			primary: '#171717',
			'primary-foreground': '#fafafa',
			secondary: '#f5f5f5',
			'secondary-foreground': '#171717',
			muted: '#f5f5f5',
			'muted-foreground': '#737373',
			accent: '#f5f5f5',
			'accent-foreground': '#171717',
			destructive: '#e7000b',
			'destructive-foreground': '#ffffff',
			border: '#e5e5e5',
			input: '#e5e5e5',
			ring: '#a1a1a1',
			'chart-1': '#91c5ff',
			'chart-2': '#3a81f6',
			'chart-3': '#2563ef',
			'chart-4': '#1a4eda',
			'chart-5': '#1f3fad',
			radius: '0.625rem',
			sidebar: '#fafafa',
			'sidebar-foreground': '#0a0a0a',
			'sidebar-primary': '#171717',
			'sidebar-primary-foreground': '#fafafa',
			'sidebar-accent': '#f5f5f5',
			'sidebar-accent-foreground': '#171717',
			'sidebar-border': '#e5e5e5',
			'sidebar-ring': '#a1a1a1',
			'font-sans':
				"ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
			'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
			'font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
			'shadow-color': 'oklch(0 0 0)',
			'shadow-opacity': '0.1',
			'shadow-blur': '3px',
			'shadow-spread': '0px',
			'shadow-offset-x': '0',
			'shadow-offset-y': '1px',
			'letter-spacing': '0em',
			spacing: '0.25rem',
		},
		dark: {
			background: '#0a0a0a',
			foreground: '#fafafa',
			card: '#171717',
			'card-foreground': '#fafafa',
			popover: '#262626',
			'popover-foreground': '#fafafa',
			primary: '#e5e5e5',
			'primary-foreground': '#171717',
			secondary: '#262626',
			'secondary-foreground': '#fafafa',
			muted: '#262626',
			'muted-foreground': '#a1a1a1',
			accent: '#404040',
			'accent-foreground': '#fafafa',
			destructive: '#ff6467',
			'destructive-foreground': '#fafafa',
			border: '#282828',
			input: '#343434',
			ring: '#737373',
			'chart-1': '#91c5ff',
			'chart-2': '#3a81f6',
			'chart-3': '#2563ef',
			'chart-4': '#1a4eda',
			'chart-5': '#1f3fad',
			radius: '0.625rem',
			sidebar: '#171717',
			'sidebar-foreground': '#fafafa',
			'sidebar-primary': '#1447e6',
			'sidebar-primary-foreground': '#fafafa',
			'sidebar-accent': '#262626',
			'sidebar-accent-foreground': '#fafafa',
			'sidebar-border': '#282828',
			'sidebar-ring': '#525252',
			'font-sans':
				"ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
			'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
			'font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
			'shadow-color': 'oklch(0 0 0)',
			'shadow-opacity': '0.1',
			'shadow-blur': '3px',
			'shadow-spread': '0px',
			'shadow-offset-x': '0',
			'shadow-offset-y': '1px',
			'letter-spacing': '',
			spacing: '0.25rem',
		},
	},
};

const AIRBNB_PRESET: ThemePreset = {
	label: 'Airbnb',
	id: 'airbnb',
	source: 'BUILT_IN',
	styles: {
		light: {
			background: '#ffffff',
			foreground: '#222222',
			card: '#ffffff',
			'card-foreground': '#222222',
			popover: '#ffffff',
			'popover-foreground': '#222222',
			primary: '#FF5A5F',
			'primary-foreground': '#ffffff',
			secondary: '#f7f7f7',
			'secondary-foreground': '#222222',
			muted: '#f7f7f7',
			'muted-foreground': '#717171',
			accent: '#F2F2F2',
			'accent-foreground': '#222222',
			destructive: '#C13515',
			'destructive-foreground': '#ffffff',
			border: '#DDDDDD',
			input: '#DDDDDD',
			ring: '#FF5A5F',
			'chart-1': '#FF5A5F',
			'chart-2': '#484848',
			'chart-3': '#FC642D',
			'chart-4': '#484848',
			'chart-5': '#767676',
			radius: '0.5rem',
			sidebar: '#f7f7f7',
			'sidebar-foreground': '#222222',
			'sidebar-primary': '#FF5A5F',
			'sidebar-primary-foreground': '#ffffff',
			'sidebar-accent': '#ffffff',
			'sidebar-accent-foreground': '#222222',
			'sidebar-border': '#DDDDDD',
			'sidebar-ring': '#FF5A5F',
			'font-sans':
				"'Cereal', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
			'font-serif': '\'Cereal\', ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
			'font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
			'shadow-color': '#222222',
			'shadow-opacity': '0.08',
			'shadow-blur': '6px',
			'shadow-spread': '0px',
			'shadow-offset-x': '0',
			'shadow-offset-y': '2px',
			'letter-spacing': '-0.01em',
			spacing: '0.25rem',
		},
		dark: {
			background: '#222222',
			foreground: '#ffffff',
			card: '#2D2D2D',
			'card-foreground': '#ffffff',
			popover: '#2D2D2D',
			'popover-foreground': '#ffffff',
			primary: '#FF5A5F',
			'primary-foreground': '#ffffff',
			secondary: '#3A3A3A',
			'secondary-foreground': '#ffffff',
			muted: '#3A3A3A',
			'muted-foreground': '#B0B0B0',
			accent: '#808080',
			'accent-foreground': '#ffffff',
			destructive: '#FF6B6B',
			'destructive-foreground': '#ffffff',
			border: '#484848',
			input: '#484848',
			ring: '#FF5A5F',
			'chart-1': '#FF5A5F',
			'chart-2': '#767676',
			'chart-3': '#FC642D',
			'chart-4': '#B0B0B0',
			'chart-5': '#767676',
			radius: '0.5rem',
			sidebar: '#2D2D2D',
			'sidebar-foreground': '#ffffff',
			'sidebar-primary': '#FF5A5F',
			'sidebar-primary-foreground': '#ffffff',
			'sidebar-accent': '#3A3A3A',
			'sidebar-accent-foreground': '#ffffff',
			'sidebar-border': '#484848',
			'sidebar-ring': '#FF5A5F',
			'font-sans':
				"'Cereal', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
			'font-serif': '\'Cereal\', ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
			'font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
			'shadow-color': '#000000',
			'shadow-opacity': '0.3',
			'shadow-blur': '6px',
			'shadow-spread': '0px',
			'shadow-offset-x': '0',
			'shadow-offset-y': '2px',
			'letter-spacing': '-0.01em',
			spacing: '0.25rem',
		},
	},
};

const NOTION_PRESET: ThemePreset = {
	label: 'Notion',
	id: 'notion',
	source: 'BUILT_IN',
	styles: {
		light: {
			background: '#fefefe',
			foreground: '#2e2e2e',
			card: '#fefefe',
			'card-foreground': '#2e2e2e',
			popover: '#ffffff',
			'popover-foreground': '#2e2e2e',
			primary: '#0075de',
			'primary-foreground': '#ffffff',
			secondary: '#f7f6f3',
			'secondary-foreground': '#2e2e2e',
			muted: '#f7f6f3',
			'muted-foreground': '#898989',
			accent: '#e9e9e7',
			'accent-foreground': '#2e2e2e',
			destructive: '#DC2626',
			'destructive-foreground': '#ffffff',
			border: '#e9e9e7',
			input: '#e9e9e7',
			ring: '#0075de',
			'chart-1': '#0075de',
			'chart-2': '#D4A574',
			'chart-3': '#B5A7A0',
			'chart-4': '#898989',
			'chart-5': '#6B6B6B',
			radius: '0.375rem',
			sidebar: '#f7f6f3',
			'sidebar-foreground': '#2e2e2e',
			'sidebar-primary': '#0075de',
			'sidebar-primary-foreground': '#ffffff',
			'sidebar-accent': '#e9e9e7',
			'sidebar-accent-foreground': '#2e2e2e',
			'sidebar-border': '#e9e9e7',
			'sidebar-ring': '#0075de',
			'font-sans':
				"ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI Variable Display', 'Segoe UI', Helvetica, 'Apple Color Emoji', Arial, sans-serif, 'Segoe UI Emoji', 'Segoe UI Symbol'",
			'font-serif': 'Lyon-Text, Georgia, ui-serif, serif',
			'font-mono': 'iaWriter-Mono, Nitti, Menlo, Courier, monospace',
			'shadow-color': '#2e2e2e',
			'shadow-opacity': '0.05',
			'shadow-blur': '4px',
			'shadow-spread': '0px',
			'shadow-offset-x': '0',
			'shadow-offset-y': '1px',
			'letter-spacing': '-0.005em',
			spacing: '0.25rem',
		},
		dark: {
			background: '#191919',
			foreground: '#e9e9e7',
			card: '#2e2e2e',
			'card-foreground': '#e9e9e7',
			popover: '#2e2e2e',
			'popover-foreground': '#e9e9e7',
			primary: '#0075de',
			'primary-foreground': '#ffffff',
			secondary: '#2e2e2e',
			'secondary-foreground': '#e9e9e7',
			muted: '#2e2e2e',
			'muted-foreground': '#898989',
			accent: '#3a3a3a',
			'accent-foreground': '#e9e9e7',
			destructive: '#EF4444',
			'destructive-foreground': '#ffffff',
			border: '#3a3a3a',
			input: '#3a3a3a',
			ring: '#0075de',
			'chart-1': '#0075de',
			'chart-2': '#D4A574',
			'chart-3': '#B5A7A0',
			'chart-4': '#898989',
			'chart-5': '#6B6B6B',
			radius: '0.375rem',
			sidebar: '#2e2e2e',
			'sidebar-foreground': '#e9e9e7',
			'sidebar-primary': '#0075de',
			'sidebar-primary-foreground': '#ffffff',
			'sidebar-accent': '#3a3a3a',
			'sidebar-accent-foreground': '#e9e9e7',
			'sidebar-border': '#3a3a3a',
			'sidebar-ring': '#0075de',
			'font-sans':
				"ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI Variable Display', 'Segoe UI', Helvetica, 'Apple Color Emoji', Arial, sans-serif, 'Segoe UI Emoji', 'Segoe UI Symbol'",
			'font-serif': 'Lyon-Text, Georgia, ui-serif, serif',
			'font-mono': 'iaWriter-Mono, Nitti, Menlo, Courier, monospace',
			'shadow-color': '#000000',
			'shadow-opacity': '0.2',
			'shadow-blur': '4px',
			'shadow-spread': '0px',
			'shadow-offset-x': '0',
			'shadow-offset-y': '1px',
			'letter-spacing': '-0.005em',
			spacing: '0.25rem',
		},
	},
};

export const BUILT_IN_PRESETS: ThemePreset[] = [DEFAULT_PRESET, AIRBNB_PRESET, NOTION_PRESET];
