// @ts-check
'use strict';

/**
 * Pre-build script that generates Angular environment files from environment variables.
 *
 * Local development: create a .env file based on .env.example
 * CI/CD (Netlify): set variables in the Netlify dashboard
 *
 * Required variables:
 *   NG_APP_BASE_URL         — API base URL (e.g. https://api.example.com)
 *   NG_APP_API_URL          — API URL (e.g. https://api.example.com/api)
 *   NG_APP_GOOGLE_CLIENT_ID — Google OAuth client ID
 */

const fs = require('fs');
const path = require('path');

// Load .env file if it exists (local development). In CI, variables are injected by Netlify.
const envFilePath = path.resolve(__dirname, '..', '.env');
if (fs.existsSync(envFilePath)) {
	require('dotenv').config({ path: envFilePath, quiet: true });
}

const REQUIRED_VARS = ['NG_APP_BASE_URL', 'NG_APP_API_URL', 'NG_APP_GOOGLE_CLIENT_ID'];

// Validate all required variables are present
const missing = REQUIRED_VARS.filter((key) => !process.env[key]);
if (missing.length > 0) {
	console.error('\n[set-env] ERROR: Missing required environment variables:');
	missing.forEach((key) => console.error(`  - ${key}`));
	console.error('\nFor local development, create a .env file from .env.example:');
	console.error('  cp .env.example .env\n');
	process.exit(1);
}

const baseUrl = process.env['NG_APP_BASE_URL'];
const apiUrl = process.env['NG_APP_API_URL'];
const googleClientId = process.env['NG_APP_GOOGLE_CLIENT_ID'];
// Optional: defaults to true; set to "false" on integration Netlify site
const isProduction = process.env['NG_APP_PRODUCTION'] !== 'false';

const environmentsDir = path.resolve(__dirname, '..', 'src', 'environments');
fs.mkdirSync(environmentsDir, { recursive: true });

const productionContent = `// This file is generated by scripts/set-env.js — DO NOT edit manually or commit it.
export const environment = {
	production: ${isProduction},
\tbaseUrl: '${baseUrl}',
\tapiUrl: '${apiUrl}',
\tgoogleClientId: '${googleClientId}',
};
`;

const developmentContent = `// This file is generated by scripts/set-env.js — DO NOT edit manually or commit it.
export const environment = {
\tproduction: false,
\tbaseUrl: '${baseUrl}',
\tapiUrl: '${apiUrl}',
\tgoogleClientId: '${googleClientId}',
};
`;

fs.writeFileSync(path.join(environmentsDir, 'environment.ts'), productionContent);
fs.writeFileSync(path.join(environmentsDir, 'environment.development.ts'), developmentContent);

console.log('[set-env] Environment files generated successfully.');
